

-- 1. Warehouse
CREATE WAREHOUSE IF NOT EXISTS RETAIL_HOL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE RETAIL_HOL_WH;

-- 2. Database and Schemas
CREATE DATABASE IF NOT EXISTS HOL_ONLINE_RETAIL;

USE DATABASE HOL_ONLINE_RETAIL;

CREATE SCHEMA IF NOT EXISTS DATA;
CREATE SCHEMA IF NOT EXISTS TOOLS;
CREATE SCHEMA IF NOT EXISTS AGENTS;

-- 3. File Format for CSV loading
USE SCHEMA DATA;

CREATE OR REPLACE FILE FORMAT RETAIL_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  SKIP_HEADER = 1;

-- 4. Stages
CREATE STAGE IF NOT EXISTS RETAIL_DATA_STAGE
  FILE_FORMAT = RETAIL_CSV_FORMAT;

CREATE STAGE IF NOT EXISTS RETAIL_SKILLS_STAGE;

-- 5. Dimension Tables
CREATE TABLE IF NOT EXISTS DATA.DIM_CUSTOMER (
  CUSTOMER_ID   VARCHAR(20)  PRIMARY KEY,
  COUNTRY       VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS DATA.DIM_PRODUCT (
  STOCK_CODE    VARCHAR(20)  PRIMARY KEY,
  DESCRIPTION   VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS DATA.DIM_COUNTRY (
  COUNTRY       VARCHAR(100) PRIMARY KEY,
  REGION        VARCHAR(100)
);

-- 6. Fact Table
CREATE TABLE IF NOT EXISTS DATA.FACT_TRANSACTIONS (
  TRANSACTION_ID  VARCHAR(50)  PRIMARY KEY,
  INVOICE_NO      VARCHAR(20),
  STOCK_CODE      VARCHAR(20)  REFERENCES DATA.DIM_PRODUCT(STOCK_CODE),
  CUSTOMER_ID     VARCHAR(20)  REFERENCES DATA.DIM_CUSTOMER(CUSTOMER_ID),
  COUNTRY         VARCHAR(100) REFERENCES DATA.DIM_COUNTRY(COUNTRY),
  INVOICE_DATE    TIMESTAMP,
  QUANTITY        INTEGER,
  UNIT_PRICE      FLOAT,
  REVENUE         FLOAT,
  IS_CANCELLATION BOOLEAN
);

-- 7. Verify
SHOW TABLES IN SCHEMA DATA;